### ISSUE TITLE
work 异常退出 || work 自动下线

### ISSUE THREAD

**Issue by zhihuba** [hanc00l/nemo_go#17]
# work 异常退出
- 使用docker 自动部署
# 意外退出代码
```bash
time="2022-03-14 01:56:32" level=info msg="Crawling GET https://xxxx.com.cn/user/application/text/text/html"
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 523366 [running]:
sync.(*WaitGroup).Wait(0xea94aa)
        sync/waitgroup.go:132 +0xa5
github.com/hanc00l/crawlergo/pkg/engine.(*Tab).Start.func3()
        github.com/hanc00l/crawlergo@v0.4.3/pkg/engine/tab.go:232 +0x2b
created by github.com/hanc00l/crawlergo/pkg/engine.(*Tab).Start
        github.com/hanc00l/crawlergo@v0.4.3/pkg/engine/tab.go:230 +0x5cf
```
# 没找他其他下线原因。下线不一定是这个问题。已知任务量过大的时候 work %100 异常退出。还会存在服务器卡死现象。。。ssh 都连接不上去 服务器配置 2核心4G 分配了四个 work

**Comment by hanc00l** [comment]
默认一个worker是同时跑3个任务，爬虫、指纹识别、子域名爆破都是比较耗资源，建议2核心4G跑1个worker。
ssh连不上应该是多个任务把vps带宽和cpu都占完了。

**Comment by zhihuba** [comment]
大佬理解错了。。是 分别部署了4个work 每个配置都是2核心4G

**Comment by hanc00l** [comment]
这样没啥问题
